project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://erikanegrini.github.io/MedBioInfo-Blog-/ # you must change this appropriately for RSS feeds to work properly
  title: "Erika´s Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/erikanegrini
      - icon: KI website
        href: https://ki.se/en/people/erika-negrini
format:
  html:
    theme:
      - minty
    css: styles.css

execute:
  freeze: auto

metadata:
  categories: true
  

  